### ISSUE TITLE
KNX Gruppenadressen

### ISSUE THREAD

**Issue by michkalcher** [Woersty/LoxBerry-Plugin-KNXd#4]
die Gruppenadressen sind derzeit nur bis [0-15]/[0-7]/[0-255] eintragbar.
Allerdings ist der mögliche Bereich [0-31]/[0-7]/[0-255] (zumindest mit ETS5)

lg,

**Comment by Woersty** [comment]
Ok. Änderung wird eingebaut.

**Comment by Woersty** [comment]
Ab KNXd v2018.3.12
