### ISSUE TITLE
Oberfäche nicht mehr erreichbar

### ISSUE THREAD

**Issue by chris8519** [Woersty/LoxBerry-Plugin-KNXd#8]
Software error:

Cannot open logfile /opt/loxberry/log/plugins/knxd/knxd.log at /opt/loxberry/webfrontend/htmlauth/plugins/knxd/index.cgi line 62.

**Comment by Woersty** [comment]
Welche Version?

**Comment by Woersty** [comment]
Sollte ab v2018.3.18 gehen. Stell ich mal eben online.

**Comment by Woersty** [comment]
Achso, 1.0.4 ist noch Pre-Release. 
Wenn du das nicht willst, musst du noch etwas warten oder die zip Datei öffnen und die plugin.cfg editieren.

**Comment by chris8519** [comment]
1.0.4 aber jetzt geht es ... ist der rpi- mointor zwingend erforderlich ?
log sieht noch so aus :

Uncommenting the KNXd section in rpimonitor if installed
find: ‘/opt/loxberry/data/plugins/rpi_monitor*/’: No such file or directory
find: ‘/opt/loxberry/data/plugins/rpi_monitor*/’: No such file or directory
find: ‘/opt/loxberry/data/plugins/rpi_monitor*/’: No such file or directory
Restart rpimonitor if installed
Plugin modification already done.
Configure KNXd to use KNXD_OPTS="-b ipt:miniserver"
Check, if KNXd Control Daemon is running
Process ID 726 found, no action
Try to restart KNXd
Job for knxd.service failed because the control process exited with error code.
See "systemctl status knxd.service" and "journalctl -xe" for details.
KNXd cannot be started. That's bad.
Oh oh, I had problems. Please read the Plugin-Logfile for details.

**Comment by Woersty** [comment]
Ist er nicht, der rpi-monitor.
Ich passe die Scripte mal an, dass es ausgeblendet wird.
KNXd cannot be started. That's bad.  => Das ist normal, muss ich mal irgendwie besser abfangen.
Er installiert zu diesem Zeitpunkt noch.
Schau ich mir an.

**Comment by Woersty** [comment]
Gerade nochmal gelesen... hast du denn die IP vom KNX Gateway konfiguriert?

**Comment by Woersty** [comment]
Versuch mal die PreRelease Version v2018.3.18.2

**Comment by Woersty** [comment]
Wenn die bei dir geht, bringe ich morgen eine v2018.3.19 als Release raus

**Comment by chris8519** [comment]
Hostnamen vom miniserver ... mit der ip geht es. 
Nach dem Neustart ist der fehler auch nicht mehr aufgetaucht und ich konnte auf die Oberfläche zugereifen
